### ISSUE TITLE
GoogleOCR is not threadsafe (v0.x)

### ISSUE THREAD

**Issue by phschoepf** [deepopinion/ocr_wrapper#10]
GoogleOCR writes to a per-instance `self.extra` dict which is shared for parallel requests. This leads to data inconsistency when running in parallel, such as `ocr_wrapper.compat.bboxs2dicts` failing the `assert len(bboxes) == len(confidences)` check.

**Comment by phschoepf** [comment]
BTW I think this also applies to other OCR classes, I just tested it on Google OCR

**Comment by Paethon** [comment]
Same for all the others. Just approved #12 that you proposed that fixes this.
