### ISSUE TITLE
BBoxOverlapChecker causes tracing spam

### ISSUE THREAD

**Issue by phschoepf** [deepopinion/ocr_wrapper#26]
https://github.com/deepopinion/ocr_wrapper/blob/002b1ec904e1d19c97bc992a5f8558e8581b904d/ocr_wrapper/google_azure_ocr.py#L298

is called very often (often 1000s of times for one document) and causes lots of very short traces to be logged.

**Comment by Paethon** [comment]
Weird. I thought I already removed that ... :confused:
